-- MySQL Script generated by MySQL Workbench
-- Tue Jul 10 10:44:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employee_id` INT(5) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(20) NULL DEFAULT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `phone_num` INT(11) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `employee_id_UNIQUE` (`employee_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`application_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`application_data` (
  `application_id` INT(5) NOT NULL AUTO_INCREMENT,
  `employee_id` INT(5) NULL DEFAULT NULL,
  `is_recertification` TINYINT(4) NOT NULL,
  `candidate_comments` VARCHAR(1440) NULL DEFAULT NULL,
  `special_achivements` VARCHAR(1440) NULL DEFAULT NULL,
  `enguagements_since` TINYINT(4) NULL DEFAULT NULL,
  `expired` TINYINT(4) NULL DEFAULT NULL,
  `emp_location` VARCHAR(32) NULL DEFAULT NULL,
  `emp_city` VARCHAR(32) NULL DEFAULT NULL,
  `emp_country` VARCHAR(32) NULL DEFAULT NULL,
  `emp_job_role` VARCHAR(45) NULL DEFAULT NULL,
  `emp_job_level` VARCHAR(45) NULL DEFAULT NULL,
  `emp_job_role_group` VARCHAR(45) NULL DEFAULT NULL,
  `emp_current_expire_date` DATE NULL DEFAULT NULL,
  `emp_it_experience` INT(5) NULL DEFAULT NULL,
  `emp_sevice_line` VARCHAR(45) NULL DEFAULT NULL,
  `emp_discipline` VARCHAR(45) NULL DEFAULT NULL,
  `emp_pratice` VARCHAR(45) NULL DEFAULT NULL,
  `emp_specialism` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`application_id`),
  INDEX `emoloyee_id_idx` (`employee_id` ASC),
  CONSTRAINT `ad_emoloyee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`certification_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`certification_record` (
  `employee_id` INT(5) NOT NULL,
  `certification_id` INT(5) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL DEFAULT NULL,
  `expiry_date` DATE NULL DEFAULT NULL,
  `grade` VARCHAR(3) NULL DEFAULT NULL,
  `re_certificated` TINYINT(4) NULL DEFAULT NULL,
  `currentLevel` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`certification_id`),
  INDEX `employee_id_idx` (`employee_id` ASC),
  CONSTRAINT `cr_employee_id`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`qualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`qualification` (
  `qualification_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(10) NOT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `level_num` INT(11) NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`qualification_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 59
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`personal_qualification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personal_qualification` (
  `qualification_id` INT(5) NOT NULL,
  `application_id` INT(5) NOT NULL,
  `level` INT(11) NOT NULL,
  `explanation` VARCHAR(200) NOT NULL,
  INDEX `employee_id_idx` (`application_id` ASC),
  INDEX `QualificationID` (`qualification_id` ASC),
  CONSTRAINT `QualificationID`
    FOREIGN KEY (`qualification_id`)
    REFERENCES `mydb`.`qualification` (`qualification_id`),
  CONSTRAINT `pq_application_id`
    FOREIGN KEY (`application_id`)
    REFERENCES `mydb`.`application_data` (`application_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reference` (
  `application_id` INT(5) NOT NULL,
  `refer_employee_id` INT(5) NOT NULL,
  UNIQUE INDEX `application_ref_idx` (`application_id` ASC, `refer_employee_id` ASC),
  INDEX `refer_employee_id_idx` (`refer_employee_id` ASC),
  CONSTRAINT `application_id`
    FOREIGN KEY (`application_id`)
    REFERENCES `mydb`.`application_data` (`application_id`),
  CONSTRAINT `refer_employee_id`
    FOREIGN KEY (`refer_employee_id`)
    REFERENCES `mydb`.`employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`temporary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`temporary` (
  `tmp_application_id` INT(5) NOT NULL AUTO_INCREMENT,
  `employee_id` INT(5) NULL DEFAULT NULL,
  `tmp_application_data` VARCHAR(20000) NULL DEFAULT NULL,
  PRIMARY KEY (`tmp_application_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`work_experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`work_experience` (
  `experience_id` INT(5) NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `job_title` VARCHAR(128) NULL DEFAULT NULL,
  `job_duty` VARCHAR(1440) NULL DEFAULT NULL,
  `result` VARCHAR(1440) NULL DEFAULT NULL,
  `application_id` INT(5) NOT NULL,
  PRIMARY KEY (`experience_id`),
  INDEX `we_application_id_idx` (`application_id` ASC),
  CONSTRAINT `we_application_id`
    FOREIGN KEY (`application_id`)
    REFERENCES `mydb`.`application_data` (`application_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
