/*
-- Query: SELECT * FROM mydb.qualification
LIMIT 0, 1000

-- Date: 2018-07-09 15:12
*/
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (1,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":1,\"desc\":\"Candidate should be in a client-serving role.\\n  Individuals working on internal assignments must be scheduled to rotate back\\n  to a client serving role in order to apply for certification.  No line management will be nominated.\\n  Candidate’s career objectives are focused on EM roles. The candidate\\n  explicitly expresses his will to belong to the EM Community.\"}]',5,'Focus on EM');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (2,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":1,\"desc\":\"Candidate must have at least 1 year of experience\\n  working at Capgemini to qualify.  With\\n  less than 4 months at Capgemini, \\\"probationary\\\" certification is\\n  possible provided if Candidate can demonstrate experience requirements\\n  through previous external roles.  In\\n  this case, the EM The Capgemini Way course is considered mandatory.\"}]',5,'Capgemini History');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (3,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":1,\"desc\":\"Attend community meetings, volunteer for community activities.\"},{\"level\":2,\"desc\":\"Coaching/mentoring of lower level EMs, attendcommunity meetings, volunteer for community activities, participating in theEMCB, designing and conducting training for EMs.\"}]',5,'Actively participate in the community\r');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (4,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":3,\"desc\":\"Candidate must have experience in working in a multi-cultural environment (in multi-cultural engagements, working with other nationalities, participating in a flying squad, conducting a  training with international participants etc.).\"}]',5,'Culture');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (5,'QUAL','[{\"level\":0,\"desc\":\"Candidate should be proficient in the main language spoken in their country.\"},{\"level\":2,\"desc\":\"Candidate should be proficient in the languages spoken in their country and in business English (speaking, reading & writing).\"}]',5,'Language');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (6,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":2,\"desc\":\"Candidate must have multi-site, preferably international experience (although this may be completed in the Candidate\'s own Region).\"},{\"level\":4,\"desc\":\"Candidate must be willing to accept international assignments.\"}]',5,'International assignment');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (7,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":1,\"desc\":\"Leading role in at least 1 successful pursuit\"},{\"level\":2,\"desc\":\"Leading role in at least 2 successful pursuit\"},{\"level\":3,\"desc\":\"Leading role in at least 3 successful pursuit\"},{\"level\":4,\"desc\":\"Leading role in at least 3 successful pursuit\"}]',5,'Participation in pursuit');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (8,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":1,\"desc\":\"EM with full responsibility for at least 1 successful Level 1 project during the past 3 years.\"},{\"level\":2,\"desc\":\"EM with full responsibility for at least 1 successful Level 2 project during the past 3 years.\"},{\"level\":3,\"desc\":\"EM with full responsibility for at least 1 successful Level 3 project during the past 5 years.\"},{\"level\":4,\"desc\":\"EM with full responsibility for at least 2 successful Level 3 project during the past 5 years.\"}]',5,'Role in engagements');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (9,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":1,\"desc\":\"Re-fresher training completed.\"}]',5,'Re-fresher training');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (10,'QUAL','[{\"level\":0,\"desc\":\"Level 0 Exam passed.\"},{\"level\":1,\"desc\":\"Level 1 Exam passed.\"},{\"level\":2,\"desc\":\"Level 2 Exam passed.\"},{\"level\":3,\"desc\":\"Level 3 Exam passed.\"},{\"level\":4,\"desc\":\"N.a.\"}]',5,'Exam');
INSERT INTO `qualification` (`qualification_id`,`type`,`description`,`level_num`,`title`) VALUES (11,'QUAL','[{\"level\":0,\"desc\":\"No minimum requirement.\"},{\"level\":3,\"desc\":\"Candidate certified at level 2 or 3  (for recertification) or, for probationary certification, joined Capgemini within last 4 months.\"},{\"level\":4,\"desc\":\"Candidate certified at level 3.\"}]',5,'Certification');

INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '0', 'Which of the following face-to-face trainings, or equivalent trainings, did the Candidate attend during his/her career?');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', 'EM Practitioner');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', 'EM Advanced');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', 'OSM Outsourcing Service Management or USM training');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', 'EM@B2R (Build-to-Run)');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', 'EM the Capgemini Way');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', 'H2C (how to work with a client)');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', 'EM Mastering Complex Engagements or Large Complex Engagements');
INSERT INTO `mydb`.`qualification` (`type`, `level_num`, `title`) VALUES ('TRAIN', '2', '\"Did the Candidate complete all mandatory elearnings as displayed on the Global EM Talent page?\nIf so, please incorporate a pdf of your Transcript in MyLearning which shows that you have completed these trainings and additional certificates as needed.\n\"');

INSERT INTO `mydb`.`qualification` (`type`, `description`, `level_num`, `title`) VALUES ('CUR_CERT', '{\"probationary\":[2,3]}', '7', 'Current/former certification level');
INSERT INTO `mydb`.`qualification` (`type`, `description`, `level_num`, `title`) VALUES ('APPLY_CERT', '{\"probationary\":[2,3]}', '7', 'Applying for EM Certification level');
